<template>
    <AiToolWrapper :remaining="remainingRequests"><div class="bg-white dark:bg-surface-800 p-6 rounded-2xl shadow-sm border border-surface-200 dark:border-surface-700"><div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="space-y-4">
        <div><label class="block text-sm font-medium text-surface-700 dark:text-surface-300 mb-2">Job Title / Role</label><input v-model="inputText" type="text" class="block w-full rounded-xl border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-surface-900 dark:text-white focus:ring-primary-500 focus:border-primary-500 text-base p-4" placeholder="e.g. Senior Laravel Developer" /></div>
        <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Company Name (optional)</label><input v-model="options.company" type="text" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-2.5" placeholder="Company" /></div>
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Employment Type</label><select v-model="options.type" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-white dark:bg-surface-800 text-sm focus:ring-primary-500 focus:border-primary-500"><option v-for="t in ['Full-time','Part-time','Contract','Remote','Hybrid']" :key="t" :value="t">{{ t }}</option></select></div>
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Experience Level</label><select v-model="options.level" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-white dark:bg-surface-800 text-sm focus:ring-primary-500 focus:border-primary-500"><option v-for="l in ['Entry','Mid','Senior','Manager','Director']" :key="l" :value="l">{{ l }}</option></select></div>
            <LanguageSelector v-model="options.language" />
        </div>
        <div><label class="block text-xs font-medium text-surface-500 mb-1">Required Skills</label><textarea v-model="options.skills" rows="2" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-3 resize-none" placeholder="Laravel, Vue.js, MySQL..."></textarea></div>
        <div><label class="block text-xs font-medium text-surface-500 mb-1">Key Responsibilities (brief)</label><textarea v-model="options.responsibilities" rows="2" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-3 resize-none" placeholder="Lead development, review code..."></textarea></div>
        <div><label class="block text-xs font-medium text-surface-500 mb-1">Salary Range (optional)</label><input v-model="options.salary" type="text" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-2.5" placeholder="e.g. $80K-$120K" /></div>
        <label class="flex items-center gap-2 cursor-pointer"><input type="checkbox" v-model="options.ats" class="rounded border-surface-300 dark:border-surface-600 text-primary-600 focus:ring-primary-500" /><span class="text-sm text-surface-700 dark:text-surface-300">Make ATS-Friendly</span></label>
        <button @click="handleGenerate" :disabled="!inputText || isLoading" class="w-full py-3 px-4 bg-gradient-to-r from-primary-600 to-purple-600 hover:from-primary-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm"><svg v-if="isLoading" class="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>{{ isLoading ? 'Writing JD...' : 'Generate Job Description' }}</button>
        <div v-if="error" class="p-3 bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 rounded-lg text-sm border border-red-100 dark:border-red-800">{{ error }}</div>
    </div><AiOutputCard :content="result" :loading="isLoading" :language="options.language" title="Job Description" loadingText="Writing job description..." :showCopy="true" :showDownload="true" downloadFilename="job-description.txt" /></div></div></AiToolWrapper>
</template>
<script setup>
import { ref, computed } from 'vue';import { usePage } from '@inertiajs/vue3';import AiToolWrapper from '@/Components/Ai/AiToolWrapper.vue';import AiOutputCard from '@/Components/Ai/AiOutputCard.vue';import LanguageSelector from '@/Components/Ai/LanguageSelector.vue';import { useAiRequest } from '@/Composables/useAiRequest';
const props = defineProps({ tool: Object });const page = usePage();const isPro = computed(() => page.props.auth.user?.is_pro || false);const maxLength = computed(() => { const c = props.tool.ai_config; return c ? (isPro.value ? c.max_input_length_pro : c.max_input_length_free) : 1000; });
const inputText = ref('');const options = ref({ company: '', type: 'Full-time', level: 'Mid', language: 'english_us', skills: '', responsibilities: '', salary: '', ats: true });
const { isLoading, error, result, remainingRequests, generate } = useAiRequest();const handleGenerate = () => { generate(props.tool.slug, inputText.value, options.value); };
</script>
