<template>
    <AiToolWrapper :remaining="remainingRequests"><div class="bg-white dark:bg-surface-800 p-6 rounded-2xl shadow-sm border border-surface-200 dark:border-surface-700"><div class="grid grid-cols-1 lg:grid-cols-2 gap-6"><div class="space-y-4">
        <div><label class="block text-sm font-medium text-surface-700 dark:text-surface-300 mb-2">Story Idea / Premise</label><textarea v-model="inputText" rows="3" :maxlength="maxLength" class="block w-full rounded-xl border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-surface-900 dark:text-white focus:ring-primary-500 focus:border-primary-500 text-base p-4 resize-y" placeholder="Enter your story idea in one line..."></textarea></div>
        <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Genre</label><select v-model="options.genre" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-white dark:bg-surface-800 text-sm focus:ring-primary-500 focus:border-primary-500"><option v-for="g in genres" :key="g" :value="g">{{ g }}</option></select></div>
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Length</label><select v-model="options.length" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-white dark:bg-surface-800 text-sm focus:ring-primary-500 focus:border-primary-500"><option value="Flash Fiction (~300 words)">Flash Fiction (~300w)</option><option value="Short Story (~800 words)">Short Story (~800w)</option><option value="Long Story (~1500 words)" :disabled="!isPro">Long Story (~1500w) {{ !isPro ? '🔒 Pro' : '' }}</option></select></div>
            <div><label class="block text-xs font-medium text-surface-500 mb-1">Ending Type</label><select v-model="options.ending" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-white dark:bg-surface-800 text-sm focus:ring-primary-500 focus:border-primary-500"><option v-for="e in endings" :key="e" :value="e">{{ e }}</option></select></div>
            <LanguageSelector v-model="options.language" />
        </div>
        <div class="grid grid-cols-2 gap-4"><div><label class="block text-xs font-medium text-surface-500 mb-1">Character Name (optional)</label><input v-model="options.character" type="text" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-2.5" placeholder="Main character" /></div><div><label class="block text-xs font-medium text-surface-500 mb-1">Setting (optional)</label><input v-model="options.setting" type="text" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-2.5" placeholder="Location" /></div></div>
        <div><label class="block text-xs font-medium text-surface-500 mb-1">Plot Points (optional)</label><textarea v-model="options.plot_points" rows="2" class="block w-full rounded-lg border-surface-300 dark:border-surface-600 bg-surface-50 dark:bg-surface-900 text-sm p-3 resize-none" placeholder="Key plot points..."></textarea></div>
        <button @click="handleGenerate" :disabled="!inputText || isLoading" class="w-full py-3 px-4 bg-gradient-to-r from-primary-600 to-purple-600 hover:from-primary-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-medium rounded-xl transition-colors flex items-center justify-center gap-2 shadow-sm"><svg v-if="isLoading" class="animate-spin w-5 h-5" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>{{ isLoading ? 'Writing Story...' : 'Generate Story' }}</button>
        <div v-if="error" class="p-3 bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 rounded-lg text-sm border border-red-100 dark:border-red-800">{{ error }}</div>
    </div>
    <AiOutputCard :content="result" :loading="isLoading" :language="options.language" title="Your Story" loadingText="Writing your story..." :showCopy="true" :showDownload="true" downloadFilename="story.txt" /></div></div></AiToolWrapper>
</template>
<script setup>
import { ref, computed } from 'vue';import { usePage } from '@inertiajs/vue3';import AiToolWrapper from '@/Components/Ai/AiToolWrapper.vue';import AiOutputCard from '@/Components/Ai/AiOutputCard.vue';import LanguageSelector from '@/Components/Ai/LanguageSelector.vue';import { useAiRequest } from '@/Composables/useAiRequest';
const props = defineProps({ tool: Object });const page = usePage();const isPro = computed(() => page.props.auth.user?.is_pro || false);const maxLength = computed(() => { const c = props.tool.ai_config; return c ? (isPro.value ? c.max_input_length_pro : c.max_input_length_free) : 1000; });
const genres = ['Romance','Thriller','Comedy','Horror','Drama','Sci-Fi','Fantasy','Islamic Story','Children\'s Story'];
const endings = ['Happy','Sad','Twist','Open-ended','Moral lesson'];
const inputText = ref('');const options = ref({ genre: 'Drama', length: 'Short Story (~800 words)', ending: 'Happy', language: 'english_us', character: '', setting: '', plot_points: '' });
const { isLoading, error, result, remainingRequests, generate } = useAiRequest();const handleGenerate = () => { generate(props.tool.slug, inputText.value, options.value); };
</script>
